---
title: "R Notebook"
output: html_notebook
---

```{r}
personal<-read.csv("C:/Users/jack1/Desktop/퍼스널케어.csv")
frozen<-read.csv("C:/Users/jack1/Desktop/냉동식품.csv")
pet<-read.csv("C:/Users/jack1/Desktop/애완용품.csv")
cosmetic<-read.csv("C:/Users/jack1/Desktop/화장품.csv")
health<-read.csv("C:/Users/jack1/Desktop/건강식품.csv")
summary(personal)
summary(frozen)
summary(pet)
summary(cosmetic)
summary(health)

```






```{r}
B<-subset(cosmetic,CLAC2_NM=="남성케어")
C<-subset(cosmetic,CLAC2_NM=="메이크업")
D<-subset(cosmetic,CLAC2_NM=="미용소품")
E<-subset(cosmetic,CLAC2_NM=="선케어")
F<-subset(cosmetic,CLAC2_NM=="스킨케어")
G<-subset(cosmetic,CLAC2_NM=="향수")
B.num<-nlevels(as.factor(B$CLNT_ID))
C.num<-nlevels(as.factor(C$CLNT_ID))
D.num<-nlevels(as.factor(D$CLNT_ID))
E.num<-nlevels(as.factor(E$CLNT_ID))
F.num<-nlevels(as.factor(F$CLNT_ID))
G.num<-nlevels(as.factor(G$CLNT_ID))

###U score, 가중치 둘
##U score는 상품을 얼마나 선호하는지에 대한 Ultimate, P는 평균 대
U1<-round(dim(B)*mean(B$PD_BUY_CT))[1]
U2<-round(dim(C)*mean(C$PD_BUY_CT))[1]
U3<-round(dim(D)*mean(D$PD_BUY_CT))[1]
U4<-round(dim(E)*mean(E$PD_BUY_CT))[1]
U5<-round(dim(F)*mean(F$PD_BUY_CT))[1]
U6<-round(dim(G)*mean(G$PD_BUY_CT))[1]
U.mean<-(U1+U2+U3+U4+U5+U6)/6
P1<-U1/U.mean
P2<-U2/U.mean
P3<-U3/U.mean
P4<-U4/U.mean
P5<-U5/U.mean
P6<-U6/U.mean

M1<-U1/B.num
M2<-U2/C.num
M3<-U3/D.num
M4<-U4/E.num
M5<-U5/F.num
M6<-U6/G.num
c(U1,U2,U3,U4,U5,U6)
c(P1,P2,P3,P4,P5,P6)
c(M1,M2,M3,M4,M5,M6)

```



```{r}
B1<-subset(personal,CLAC2_NM=="구강케어")
C1<-subset(personal,CLAC2_NM=="바디케어")
D1<-subset(personal,CLAC2_NM=="여성위생용품")
E1<-subset(personal,CLAC2_NM=="핸드/풋케어")
F1<-subset(personal,CLAC2_NM=="헤어케어")

B.num1<-nlevels(as.factor(B1$CLNT_ID))
C.num1<-nlevels(as.factor(C1$CLNT_ID))
D.num1<-nlevels(as.factor(D1$CLNT_ID))
E.num1<-nlevels(as.factor(E1$CLNT_ID))
F.num1<-nlevels(as.factor(F1$CLNT_ID))


###U score, 가중치 둘
##U score는 상품을 얼마나 선호하는지에 대한 Ultimate, P는 평균 대
U11<-round(dim(B1)*mean(B1$PD_BUY_CT))[1]
U21<-round(dim(C1)*mean(C1$PD_BUY_CT))[1]
U31<-round(dim(D1)*mean(D1$PD_BUY_CT))[1]
U41<-round(dim(E1)*mean(E1$PD_BUY_CT))[1]
U51<-round(dim(F1)*mean(F1$PD_BUY_CT))[1]
U.mean1<-(U11+U21+U31+U41+U51)/5
P11<-U11/U.mean1
P21<-U21/U.mean1
P31<-U31/U.mean1
P41<-U41/U.mean1
P51<-U51/U.mean1

M11<-U11/B.num1
M21<-U21/C.num1
M31<-U31/D.num1
M41<-U41/E.num1
M51<-U51/F.num1
c(U11,U21,U31,U41,U51)
c(P11,P21,P31,P41,P51)
c(M11,M21,M31,M41,M51)
```



```{r}
B2<-subset(pet,CLAC2_NM=="고양이용품")
C2<-subset(pet,CLAC2_NM=="애견용품")


B.num2<-nlevels(as.factor(B2$CLNT_ID))
C.num2<-nlevels(as.factor(C2$CLNT_ID))

###U score, 가중치 둘
##U score는 상품을 얼마나 선호하는지에 대한 Ultimate, P는 평균 대
U12<-round(dim(B2)*mean(B2$PD_BUY_CT))[1]
U22<-round(dim(C2)*mean(C2$PD_BUY_CT))[1]

U.mean2<-(U12+U22)/2
P12<-U12/U.mean2
P22<-U22/U.mean2

M12<-U11/B.num2
M22<-U21/C.num2

c(U12,U22)
c(P12,P22)
c(M12,M22)
```


```{r}
B4<-subset(health,CLAC2_NM=="건강보조식품")
C4<-subset(health,CLAC2_NM=="건강진액")
D4<-subset(health,CLAC2_NM=="영양제")
E4<-subset(health,CLAC2_NM=="홍삼/인삼가공식품")

B.num4<-nlevels(as.factor(B4$CLNT_ID))
C.num4<-nlevels(as.factor(C4$CLNT_ID))
D.num4<-nlevels(as.factor(D4$CLNT_ID))
E.num4<-nlevels(as.factor(E4$CLNT_ID))



###U score, 가중치 둘
##U score는 상품을 얼마나 선호하는지에 대한 Ultimate, P는 평균 대
U14<-round(dim(B4)*mean(B4$PD_BUY_CT))[1]
U24<-round(dim(C4)*mean(C4$PD_BUY_CT))[1]
U34<-round(dim(D4)*mean(D4$PD_BUY_CT))[1]
U44<-round(dim(E4)*mean(E4$PD_BUY_CT))[1]

U.mean4<-(U14+U24+U34+U44)/4
P14<-U14/U.mean4
P24<-U24/U.mean4
P34<-U34/U.mean4
P44<-U44/U.mean4

M14<-U14/B.num4
M24<-U24/C.num4
M34<-U34/D.num4
M44<-U44/E.num4

c(U14,U24,U34,U44)
c(P14,P24,P34,P44)
c(M14,M24,M34,M44)
```


```{r}
B5<-subset(frozen,CLAC3_NM=="냉동만두")
C5<-subset(frozen,CLAC3_NM=="냉동밥")
D5<-subset(frozen,CLAC3_NM=="냉동국탕류")
E5<-subset(frozen,CLAC3_NM=="냉동핫도그")
F5<-subset(frozen,CLAC3_NM=="냉동튀김")
G5<-subset(frozen,CLAC3_NM=="기타냉동간편식")


B.num5<-nlevels(as.factor(B5$CLNT_ID))
C.num5<-nlevels(as.factor(C5$CLNT_ID))
D.num5<-nlevels(as.factor(D5$CLNT_ID))
E.num5<-nlevels(as.factor(E5$CLNT_ID))
F.num5<-nlevels(as.factor(F5$CLNT_ID))
G.num5<-nlevels(as.factor(G5$CLNT_ID))

###U score, 가중치 둘
##U score는 상품을 얼마나 선호하는지에 대한 Ultimate, P는 평균 대
U15<-round(dim(B5)*mean(B5$PD_BUY_CT))[1]
U25<-round(dim(C5)*mean(C5$PD_BUY_CT))[1]
U35<-round(dim(D5)*mean(D5$PD_BUY_CT))[1]
U45<-round(dim(E5)*mean(E5$PD_BUY_CT))[1]
U55<-round(dim(F5)*mean(F5$PD_BUY_CT))[1]
U65<-round(dim(G5)*mean(G5$PD_BUY_CT))[1]

U.mean5<-(U15+U25+U35+U45+U55+U65)/6
P15<-U15/U.mean5
P25<-U25/U.mean5
P35<-U35/U.mean5
P45<-U45/U.mean5
P55<-U55/U.mean5
P65<-U65/U.mean5

M15<-U15/B.num5
M25<-U25/C.num5
M35<-U35/D.num5
M45<-U45/E.num5
M55<-U55/F.num5
M65<-U65/G.num5

c(U15,U25,U35,U45,U55,U65)
c(P15,P25,P35,P45,P55,P65)
c(M15,M25,M35,M45,M55,M65)
```


















